requires 'Config::IniFiles';
test_requires 'Config::Simple';
requires 'DBD::mysql';
requires 'DBI';
requires 'DBIx::Class';
requires 'Digest::SHA1';
# requires 'HTTP::Tiny';
requires 'JSON';
requires 'List::Util', '>= 1.45';
requires 'Log::Log4perl';
requires 'Moose';
requires 'MooseX::Log::Log4perl';
requires 'PerlIO::gzip';
requires 'Proc::Daemon';
requires 'SQL::Translator', '>= 0.11018';
requires 'Text::CSV';
requires 'Text::Glob';
# requires 'URI::Escape';
# requires 'XML::LibXML';
# requires 'XML::Simple';

test_requires 'Config::General';
# test_requires 'Devel::Cycle';
# test_requires 'Devel::Peek';
test_requires 'Error';
test_requires 'IO::String';
# test_requires 'PadWalker';
test_requires 'Perl::Critic::Moose';
test_requires 'Perl::Critic::Utils';
# test_requires 'Test::Differences';
test_requires 'Test::Exception';
test_requires 'Test::Perl::Critic';
test_requires 'Test::Pod::Coverage';
test_requires 'Test::Warnings';
