CREATE INDEX `fk_genome_1_idx` ON `genome` (`session_id` ASC);
CREATE INDEX `fk_assembly_1_idx` ON `assembly` (`genome_id` ASC);
CREATE INDEX `fk_assembly_2_idx` ON `assembly` (`session_id` ASC);
CREATE INDEX `name_idx` ON `gene_names` (`name` ASC);
CREATE INDEX `external_id_idx` ON `gene_names` (`external_id` ASC);
CREATE INDEX `source_idx` ON `gene_names` (`source` ASC);
CREATE INDEX `fk_gene_names_3_idx` ON `gene_names` (`session_id` ASC);
CREATE INDEX `fk_gene_1_idx` ON `gene` (`assembly_id` ASC);
CREATE INDEX `stable_id` ON `gene` (`stable_id` ASC, `stable_id_version` ASC);
CREATE INDEX `fk_gene_2_idx` ON `gene` (`session_id` ASC);
CREATE INDEX `fk_gene_3_idx` ON `gene` (`hgnc_id` ASC);
CREATE INDEX `fk_sequence_1_idx` ON `sequence` (`session_id` ASC);
CREATE INDEX `fk_transcript_2_idx` ON `transcript` (`session_id` ASC);
CREATE INDEX `fk_transcript_3_idx` ON `transcript` (`seq_checksum` ASC);
CREATE INDEX `fk_transcript_1_idx` ON `transcript` (`assembly_id` ASC);
CREATE INDEX `stable_id_version` ON `transcript` (`stable_id` ASC, `stable_id_version` ASC);
CREATE INDEX `fk_exon_2_idx` ON `exon` (`session_id` ASC);
CREATE INDEX `fk_exon_3_idx` ON `exon` (`seq_checksum` ASC);
CREATE INDEX `fk_exon_1_idx` ON `exon` (`assembly_id` ASC);
CREATE INDEX `stable_id_version` ON `exon` (`stable_id` ASC, `stable_id_version` ASC);
CREATE INDEX `fk_translation_2_idx` ON `translation` (`session_id` ASC);
CREATE INDEX `fk_translation_3_idx` ON `translation` (`seq_checksum` ASC);
CREATE INDEX `fk_translation_1_idx` ON `translation` (`assembly_id` ASC);
CREATE INDEX `stable_id_version` ON `translation` (`stable_id` ASC, `stable_id_version` ASC);
CREATE INDEX `fk_Tagset_1_idx` ON `tagset` (`session_id` ASC);
CREATE INDEX `short_name_idx` ON `tagset` (`shortname` ASC);
CREATE INDEX `transcript_id` ON `tag` (`transcript_id` ASC);
CREATE INDEX `fk_Tag_2_idx` ON `tag` (`session_id` ASC);
CREATE INDEX `fk_release_1_idx` ON `release_set` (`assembly_id` ASC);
CREATE INDEX `fk_release_2_idx` ON `release_set` (`session_id` ASC);
CREATE INDEX `fk_release_tag_1_idx` ON `release_tag` (`release_id` ASC);
CREATE INDEX `fk_release_tag_2_idx` ON `release_tag` (`session_id` ASC);
CREATE INDEX `stable_id_version_idx` ON `operon` (`stable_id` ASC, `stable_id_version` ASC);
CREATE INDEX `fk_operon_1_idx` ON `operon` (`assembly_id` ASC);
CREATE INDEX `fk_operon_2_idx` ON `operon` (`seq_checksum` ASC);
CREATE INDEX `fk_operon_3_idx` ON `operon` (`session_id` ASC);
CREATE INDEX `stable_id_version_idx` ON `operon_transcript` (`stable_id` ASC, `stable_id_version` ASC);
CREATE INDEX `fk_operon_transcript_1_idx` ON `operon_transcript` (`operon_id` ASC);
CREATE INDEX `fk_operon_transcript_2_idx` ON `operon_transcript` (`transcript_id` ASC);
CREATE INDEX `fk_operon_transcript_3_idx` ON `operon_transcript` (`session_id` ASC);
CREATE INDEX `fk_exon_transcript_1_idx` ON `exon_transcript` (`transcript_id` ASC);
CREATE INDEX `fk_exon_transcript_2_idx` ON `exon_transcript` (`exon_id` ASC);
CREATE INDEX `fk_exon_transcript_3_idx` ON `exon_transcript` (`session_id` ASC);
CREATE INDEX `fk_assembly_alias_1_idx` ON `assembly_alias` (`assembly_id` ASC);
CREATE INDEX `fk_assembly_alias_2_idx` ON `assembly_alias` (`session_id` ASC);
CREATE INDEX `fk_assembly_alias_3_idx` ON `assembly_alias` (`genome_id` ASC);
CREATE INDEX `fk_transcript_gene_1_idx` ON `transcript_gene` (`gene_id` ASC);
CREATE INDEX `fk_transcript_gene_2_idx` ON `transcript_gene` (`transcript_id` ASC);
CREATE INDEX `fk_transcript_gene_3_idx` ON `transcript_gene` (`session_id` ASC);
CREATE INDEX `fk_translation_transcript_1_idx` ON `translation_transcript` (`transcript_id` ASC);
CREATE INDEX `fk_translation_transcript_2_idx` ON `translation_transcript` (`translation_id` ASC);
CREATE INDEX `fk_translation_transcript_3_idx` ON `translation_transcript` (`session_id` ASC);
CREATE INDEX `fk_gene_release_tag_1_idx` ON `gene_release_tag` (`feature_id` ASC);
CREATE INDEX `fk_gene_release_tag_2_idx` ON `gene_release_tag` (`release_id` ASC);
CREATE INDEX `fk_transcript_release_tag_1_idx` ON `transcript_release_tag` (`feature_id` ASC);
CREATE INDEX `fk_transcript_release_tag_2_idx` ON `transcript_release_tag` (`release_id` ASC);
CREATE INDEX `fk_translation_release_tag_1_idx` ON `translation_release_tag` (`feature_id` ASC);
CREATE INDEX `fk_translation_release_tag_2_idx` ON `translation_release_tag` (`release_id` ASC);
CREATE INDEX `fk_exon_release_tag_1_idx` ON `exon_release_tag` (`feature_id` ASC);
CREATE INDEX `fk_exon_release_tag_2_idx` ON `exon_release_tag` (`release_id` ASC);
